{
    'name': 'Lui Disc',
    'version': '16.0.1.1.1',
    'author': 'Rizky',
    'depends': ['sale','sale_management','account'],
    'data': [
        'security/ir.model.access.csv',
        # 'views/res_config_view.xml',
        'views/sale_order_views.xml',
        'views/sale_view.xml',
        'views/markup_views.xml',
        'views/account_move_view.xml',
        'views/account_invoice_view.xml',
        # 'views/invoice_report.xml',
        # 'views/sale_order_report.xml',
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
}